# Gradle Properties
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Gradle Plugins
loom_version = 1.11-SNAPSHOT
moddev_version = 2.0.115
minivan_version = 0.5
versioning_version = 1.0.0
kpublish_version = 1.0.0
submodule_version = 0.11.0
remapcheck_version = 0.4.0

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version=21
minecraft_version = 1.21.10
parchment_mc_version = 1.21.10
parchment_version = 2025.10.12
yarn_version = 2
fabric_loader_version = 0.17.3
neoforge_version = 21.10.39-beta
neoform_version = 1.21.10-20251010.172816

# Mod Properties
project_version = 0.5.99+1.21.10.local
maven_group = com.kneelawk.krender
archives_base_name = krender
javadoc_package_name = com/kneelawk/krender
submodule.expansions.authors_fabric = "kneelawk", "MerchantCalico"
submodule.expansions.authors_neoforge = kneelawk, MerchantCalico
submodule.expansions.homepage = https://github.com/Kneelawk/KRender
submodule.expansions.issues = https://github.com/Kneelawk/KRender/issues
submodule.expansions.sources = https://github.com/Kneelawk/KRender
submodule.expansions.license = MIT
submodule.expansions.environment = client
submodule.expansions.loader_version_fabric = >=0.17
submodule.expansions.loader_version_neoforge = [20.10.39,)
submodule.expansions.mc_version_fabric = >=1.21- <1.22-
submodule.expansions.java_version_fabric = >=21
submodule.expansions.parent_id = krender
submodule.expansions.parent_name = KRender
submodule.expansions.parent_description = Kneelawk's Minecraft Rendering Utilities.

# Dependencies
fapi_version = 0.136.0+1.21.10
common_events_version = 1.4.0+1.21.4
submodule.expansions.common_events_version_fabric = >=1
submodule.expansions.common_events_version_neoforge = [1,)
kregistry_version = 0.3.0-alpha.1+1.21.5

# Runtime Only Dependencies
mod_menu_version = 16.0.0-rc.1

# Javadoc Dependencies
jetbrains_annotations_version = 24.0.0
