# Gradle Properties
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Gradle Plugins
loom_version = 1.14-SNAPSHOT
moddev_version = 2.0.134
minivan_version = 0.5
versioning_version = 1.0.0
kpublish_version = 1.0.0
submodule_version = 0.11.1
remapcheck_version = 0.4.0

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version=21
minecraft_version = 1.21.11
parchment_mc_version = 1.21.10
parchment_version = 2025.10.12
yarn_version = 3
fabric_loader_version = 0.18.3
neoforge_version = 21.11.13-beta
neoform_version = 1.21.11-20251209.172050

# Mod Properties
project_version = 0.7.99+1.21.11.local
maven_group = com.kneelawk.krender
archives_base_name = krender
javadoc_package_name = com/kneelawk/krender
submodule.expansions.authors_fabric = "kneelawk", "ChrysanthCow"
submodule.expansions.authors_neoforge = kneelawk, ChrysanthCow
submodule.expansions.homepage = https://github.com/Kneelawk/KRender
submodule.expansions.issues = https://github.com/Kneelawk/KRender/issues
submodule.expansions.sources = https://github.com/Kneelawk/KRender
submodule.expansions.license = MIT
submodule.expansions.environment = client
submodule.expansions.loader_version_fabric = >=0.18
submodule.expansions.loader_version_neoforge = [20.11.13-beta,)
submodule.expansions.mc_version_fabric = >=1.21- <1.22-
submodule.expansions.java_version_fabric = >=21
submodule.expansions.parent_id = krender
submodule.expansions.parent_name = KRender
submodule.expansions.parent_description = Kneelawk's Minecraft Rendering Utilities.

# Dependencies
fapi_version = 0.140.2+1.21.11
common_events_version = 1.4.0+1.21.4
submodule.expansions.common_events_version_fabric = >=1
submodule.expansions.common_events_version_neoforge = [1,)
kregistry_version = 0.3.0-alpha.1+1.21.5

# Runtime Only Dependencies
mod_menu_version = 17.0.0-beta.1

# Javadoc Dependencies
jetbrains_annotations_version = 24.0.0
