# Gradle Properties
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Gradle Plugins
loom_version = 1.9-SNAPSHOT
moddev_version = 2.0.75
versioning_version = 1.0.0
kpublish_version = 1.0.0
submodule_version = 0.7.2
remapcheck_version = 0.4.0

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version=21
minecraft_version = 1.21.4
parchment_mc_version = 1.21.4
parchment_version = 2025.01.19
fabric_loader_version = 0.16.9
neoforge_version = 21.4.68-beta
neoform_version = 1.21.4-20241203.161809

# Mod Properties
project_version = 0.2.99+1.21.4.local
maven_group = com.kneelawk.krender
archives_base_name = krender
javadoc_package_name = com/kneelawk/krender

# Dependencies
fapi_version = 0.114.3+1.21.4
common_events_version = 1.4.0+1.21.4
kregistry_version = 0.2.0+1.21.4

# Runtime Only Dependencies
mod_menu_version = 13.0.0-beta.1

# Javadoc Dependencies
jetbrains_annotations_version = 24.0.0
